<?php

namespace App\Domain\Audit;

use App\Support\EnumHelpers;

enum AuditEvent: string
{
    use EnumHelpers;

    case LEAD_ASSIGNED = 'LEAD_ASSIGNED';
    case LEAD_REASSIGNED = 'LEAD_REASSIGNED';
    case LEAD_UNASSIGNED = 'LEAD_UNASSIGNED';
    case LEADS_IMPORTED = 'LEADS_IMPORTED';
    case CALL_STARTED = 'CALL_STARTED';
    case CALL_ENDED = 'CALL_ENDED';
    case QUALIFICATION_STARTED = 'QUALIFICATION_STARTED';
    case QUALIFICATION_COMPLETED = 'QUALIFICATION_COMPLETED';
    case STATUS_CHANGED = 'STATUS_CHANGED';
    case SCORE_CHANGED = 'SCORE_CHANGED';
    case CALLBACK_SCHEDULED = 'CALLBACK_SCHEDULED';
    case NRP_REGISTERED = 'NRP_REGISTERED';
    case NOTE_ADDED = 'NOTE_ADDED';
    case USER_REGISTERED = 'USER_REGISTERED';
    case USER_APPROVED = 'USER_APPROVED';
    case USER_REJECTED = 'USER_REJECTED';
    case USER_DEACTIVATED = 'USER_DEACTIVATED';
    case USER_REACTIVATED = 'USER_REACTIVATED';
    case SCRIPT_UPDATED = 'SCRIPT_UPDATED';
}
